name: curl_converter
description: A Dart package for effortless conversion between cURL commands and Dart class.
version: 1.0.2
repository: https://github.com/utopicnarwhal/curl_converter

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  args: '>=2.3.1 <3.0.0'
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
